<a href="https://colab.research.google.com/github/Karambir06/PROJECT/blob/main/lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [ ]:
arr1=np.size([2,3])
ar=np.

In [ ]:
import numpy as np
arr=np.array([[1,3],[3,4],[4,5]])
print(arr)
print(type(arr))

[[1 3]
 [3 4]
 [4 5]]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.zeros((2,3))
print(arr1)
print(type(arr1))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
arr=np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
n=int(input())
arr2=np.ones((n,n))
print(arr2)

45
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [ ]:
arr3=np.array([2,4,5,6,7,8,93,3,4,4,5])
ar=arr3[1:5]
print(ar)

[4 5 6 7]


In [ ]:
import math
arr=np.array([2,3])
print(arr)
arr1=np.array([2,4])
print(arr1)
sum=arr+arr1
print(sum)
sq=np.sqrt(arr)
print(sq)

[2 3]
[2 4]
[4 7]
[1.41421356 1.73205081]


In [ ]:
import numpy as np
arr1=np.array([[2,3],[4,5]])
print(arr1[1][1])
arr2=np.array([[2,3,4,3,4],[3,4,5,4,5]])
print(arr2[1][4])

5
5


# Pandas

In [ ]:
list=[1,2,456,90]
n=[1,4,6,7,8]
list1=list[::-1]
if list==list1:
  print("palindrome")
else:
  print("not palindrome")


not palindrome


In [ ]:
import pandas as pd
df=pd.read_csv('iris.csv')
df.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

from matplotlib import pyplot as plt
_df_0['sepal.length'].plot(kind='hist', bins=20, title='sepal.length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['sepal.width'].plot(kind='hist', bins=20, title='sepal.width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['petal.length'].plot(kind='hist', bins=20, title='petal.length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['petal.width'].plot(kind='hist', bins=20, title='petal.width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='sepal.length', y='sepal.width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='sepal.width', y='petal.length', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='petal.length', y='petal.width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7['sepal.length'].plot(kind='line', figsize=(8, 4), title='sepal.length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['sepal.width'].plot(kind='line', figsize=(8, 4), title='sepal.width')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['petal.length'].plot(kind='line', figsize=(8, 4), title='petal.length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['petal.width'].plot(kind='line', figsize=(8, 4), title='petal.width')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [ ]:
import pandas as pd
df1=pd.read_excel('Book1.xlsx')
df1.head(5)

Name  Punjabi  Maths  Sience  Chemistry  EVS  Sciology  sankriti  Frech  \
0   ASNH       90     78      67         65   33        44        55     77   
1  KRISH       77      6      77         55   45        44        55     77   
2  HOUSE       77     65      77         55   45        44        55     77   
3  Jansh       77     65      77         55   45        44        55     77   
4   Kush       77     65      77         55   45        44        55     77   

   Spanish  Dutch  
0       77     76  
1       77     76  
2       77     76  
3       77     76  
4       77     76

In [ ]:
import pandas as pd
data={'emp_name' : ['A','B','C','D','E'],
      'emp_id' : [10,11,12,10,10],
      'emp_salary' : [31,32,33,34,35],
      'emp_branch' : ['Science','Commerce','ECE','CSE','Civil'],
      'emp_workingDays' : [41,42,43,44,45]}
df2=pd.DataFrame(data)
df2.head(5)

emp_name  emp_id  emp_salary emp_branch  emp_workingDays
0        A      10          31    Science               41
1        B      11          32   Commerce               42
2        C      12          33        ECE               43
3        D      10          34        CSE               44
4        E      10          35      Civil               45

from matplotlib import pyplot as plt
_df_32['emp_id'].plot(kind='hist', bins=20, title='emp_id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_33['emp_salary'].plot(kind='hist', bins=20, title='emp_salary')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_34['emp_workingDays'].plot(kind='hist', bins=20, title='emp_workingDays')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_35.groupby('emp_name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_36.groupby('emp_branch').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_37.plot(kind='scatter', x='emp_id', y='emp_salary', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_38.plot(kind='scatter', x='emp_salary', y='emp_workingDays', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['emp_salary']
  ys = series['emp_id']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_39.sort_values('emp_salary', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('emp_name')):
  _plot_series(series, series_name, i)
  fig.legend(title='emp_name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('emp_salary')
_ = plt.ylabel('emp_id')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['emp_salary']
  ys = series['emp_id']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_40.sort_values('emp_salary', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('emp_branch')):
  _plot_series(series, series_name, i)
  fig.legend(title='emp_branch', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('emp_salary')
_ = plt.ylabel('emp_id')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['emp_salary']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'emp_salary'}, axis=1)
              .sort_values('emp_salary', ascending=True))
  xs = counted['emp_salary']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_41.sort_values('emp_salary', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('emp_name')):
  _plot_series(series, series_name, i)
  fig.legend(title='emp_name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('emp_salary')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['emp_salary']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'emp_salary'}, axis=1)
              .sort_values('emp_salary', ascending=True))
  xs = counted['emp_salary']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_42.sort_values('emp_salary', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('emp_branch')):
  _plot_series(series, series_name, i)
  fig.legend(title='emp_branch', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('emp_salary')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_43['emp_id'].plot(kind='line', figsize=(8, 4), title='emp_id')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_44['emp_salary'].plot(kind='line', figsize=(8, 4), title='emp_salary')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_45['emp_workingDays'].plot(kind='line', figsize=(8, 4), title='emp_workingDays')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['emp_branch'].value_counts()
    for x_label, grp in _df_46.groupby('emp_name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('emp_name')
_ = plt.ylabel('emp_branch')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_47['emp_name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_47, x='emp_id', y='emp_name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_48['emp_branch'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_48, x='emp_id', y='emp_branch', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_49['emp_name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_49, x='emp_salary', y='emp_name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_50['emp_branch'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_50, x='emp_salary', y='emp_branch', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df2.info()
df2.describe()
df2.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   emp_name         5 non-null      object
 1   emp_id           5 non-null      int64 
 2   emp_salary       5 non-null      int64 
 3   emp_branch       5 non-null      object
 4   emp_workingDays  5 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes


emp_name           0
emp_id             0
emp_salary         0
emp_branch         0
emp_workingDays    0
dtype: int64